version: 2

updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'monthly'
      timezone: 'Asia/Kolkata'
    open-pull-requests-limit: 50
    rebase-strategy: 'auto'
    pull-request-branch-name:
      separator: '-'
    assignees:
      - 'Vijay431'
    commit-message:
      prefix: 'Dependency Update:'
    target-branch: 'dependency-updates'
    labels:
      - 'dependencies'
      - 'automated'
