name: Labeler
run-name: labeler 

on: pull_request

permissions:
  contents: read
  pull-requests: write

jobs:
  label:
    runs-on: ubuntu-22.04
    continue-on-error: false
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v4
      - uses: actions/labeler@v4
        with:
          sync-labels: true
          dot: true
