name: Labeler

on:
  push:
    branches-ignore:
      - master

jobs:
  label:
    runs-on: ubuntu-latest
    continue-on-error: false
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v4
      - uses: actions/labeler@v4
        with:
          repo-token: ${{ secrets.PR_TOKEN }}
          sync-labels: true
          dot: true
