name: Create Pull Request
run-name: Pull Request

permissions:
  contents: read
  pull-requests: write

on:
  push:
    branches:
      - "master"
      - "feature/*"
      - "release/*"
      - "pr/*"
      - "hotfix/*"
      - "support/*"
      - "dev"

jobs:
  pull_request:
    name: Pull Request
    continue-on-error: true
    runs-on: ubuntu-22.04
    timeout-minutes: 1
    steps:
      - uses: actions/checkout@v3
      - uses: repo-sync/pull-request@v2
        with:
          source_branch: "dev"
          destination_branch: "master"
          pr_title: "Merging changes to `master` branch"
          pr_template: ".github/create_pull_request.md"
          pr_assignee: "Vijay431"
          pr_draft: false
          pr_allow_empty: false
