name: Process
run-name: Process

permissions:
  contents: write
  packages: write

on:
  push:
    branches:
      - release
      - master

jobs:
  version:
    name: Version
    continue-on-error: false
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org
      - uses: actions/setup-dotnet@v1
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0
        with:
          versionSpec: "5.x"
      - name: Determine Version
        id: gitversion # id to later be referenced
        uses: gittools/actions/gitversion/execute@v0
      - run: |
          readonly VERSION=${{ steps.gitversion.outputs.semVer }}
          echo $VERSION
          npm install

          git config user.name "Vijay Gangatharan"
          git config user.email "42581616+Vijay431@users.noreply.github.com"

          npm version $VERSION
          git push

          npm publish
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN_PACKAGES }}
