env:
  NPM_TOKEN: ${{ secrets.NPM_TOKEN_PACKAGES }}

permissions:
  contents: read
  packages: write

on:
  push:
    branches:
      - master

jobs:
  version:
    continue-on-error: false
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
          cache: "npm"
          cache-dependency-path: "package-lock.json"
      - run: npm install
      - name: Publishing package
        run: npm publish --access=public
