name: Generate Pull Request

permissions:
  contents: read
  pull-requests: write

on:
  push:
    branches:
      - "features/*"
      - "hotfix/*"
      - "support/*"
      - "dev"

jobs:
  pull_request:
    name: pull request
    continue-on-error: true
    runs-on: ubuntu-22.04
    timeout-minutes: 1
    steps:
      - uses: actions/checkout@v3
      - name: Set short branch name
        id: vars
        run: echo ::set-output name=short_ref::${GITHUB_REF#refs/*/}
      - name: Determine destination branch
        run: |
          source_branch=${{ steps.vars.outputs.short_ref }}
          dest_branch="dev"

          if [[ $source_branch == "dev" || $source_branch == *"feature"*  ]]; then
            dest_branch="master"
          elif [[ $source_branch == *"support"* ]]; then
            dest_branch="master"
          elif [[ $source_branch == *"hotfix"* ]]; then
            dest_branch="hotfix"
          else
            dest_branch="dev"
          fi

          echo "Source Branch: $source_branch"
          echo "Destination Branch: $dest_branch"

          echo "Updating environment variables..."
          echo "DEST_BRANCH=$dest_branch" >> $GITHUB_ENV
      - name: Create Pull Request
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: ${{ env.DEST_BRANCH }}
          pr_title: "Pushing changes to ${{ env.DEST_BRANCH }}"
          pr_template: ".github/templates/PULL_REQUEST_TEMPLATE.md"
          pr_assignee: "vijay431"
          pr_draft: false
          pr_allow_empty: false
