name: 'Pull Request Script'

on:
  push:
    branches-ignore:
      - master

jobs:
  create_pull_request:
    continue-on-error: true
    runs-on: ubuntu-22.04
    timeout-minutes: 2
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get source branch name
        id: get_source_branch
        run: echo ::set-output name=branch_name::${GITHUB_REF#refs/*/}

      - name: Set destination branch name and update environment variables
        run: |
          source_branch=${{ steps.get_source_branch.outputs.branch_name }}
          destination_branch="dev"

          echo "Source Branch: $source_branch"
          echo "Destination Branch: $destination_branch"

          echo "Updating environment variables..."
          echo "SOURCE_BRANCH=$source_branch" >> $GITHUB_ENV
          echo "DEST_BRANCH=$destination_branch" >> $GITHUB_ENV

      - name: Create pull request
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: ${{ env.DEST_BRANCH }}
          pr_title: '${{ env.SOURCE_BRANCH }} → ${{ env.DEST_BRANCH }}'
          pr_template: '.github/pull_request_template.md'
          pr_assignee: ${{ github.actor }}
          pr_label: automation
          pr_draft: false
          pr_allow_empty: false
          github_token: ${{ secrets.PR_TOKEN }}
